/**
 * api-types.ts — Auto-generated TypeScript types from OpenAPI schema.
 *
 * @spec(S10.A3)
 * Generated by: npm run types:gen (in uni-guide-ai/)
 * Source: ../api/openapi.json (run `python rag2025/scripts/export_openapi.py` first)
 *
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 */

// Placeholder — actual content generated on first `npm run types:gen` run.
// CI gate enforces sync between BE schema and this file.
export type _PlaceholderEmptySchema = Record<string, never>;
